# v3.800.7
# https://virtocommerce.atlassian.net/browse/VCST-1109
name: Release

on:
  workflow_dispatch:

jobs:
  release:
    uses: VirtoCommerce/.github/.github/workflows/release.yml@v3.800.7    
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}